### ISSUE TITLE
[BUG] Resx file is not updated after editing strings.

### ISSUE THREAD

**Issue by xorxx** [scalehq/lhq#4]
**Select category**
- [X] LHQ Editor - Visual Studio Extension
- [ ] NuGet Package - `ScaleHQ.WPF.LHQ(StrongName)`
- [ ] NuGet Package - `ScaleHQ.AspNetCore.LHQ(StrongName)`

**Version**
1.2.2.0

**Visual Studio Edition**
- [X] Visual Studio Community
- [ ] Visual Studio Pro
- [ ] Visual Studio Enterprise

**Visual Studio Version**
- [ ] 2015
- [X] 2017
- [ ] 2019

**Describe Problem**
The Designer.cs file is not updated automatically after editing resources in LHQ editor. You have to disable resx generator and re-enable it again to update designer.cs.

**Comment by psulek** [comment]
Can you make sample project and send it here as ZIP? Thanks.

**Comment by xorxx** [comment]
Sorry, the project is to big to extract the relevant parts. What informations or which project parts are especially interesting?

P.S.: The update process seems not to be automatically triggered by switching generator off and on. It happened once to update right now, but I can not reproduce it.

**Comment by psulek** [comment]
And when you create new solution, and add new lhq file and try that steps, does not also stops regenerating resx? Or only on that big project?
- Do you save document to see changes regenerate? 
- Are files that are generated by LHQ readonly, in source control, or ?

Try open `Output` pane and select `LHQ Editor Code Generator` to see some more info after save.

**Comment by xorxx** [comment]
Text from output shows:
`Localization HQ Editor (version 1.2.2.0)
[INFO] C# .NET Core Generator is disabled, no output files will be generated.`

**Comment by psulek** [comment]
So yoo have disabled `C#` generator but enabled `resx` ?

**Comment by xorxx** [comment]
> So yoo have disabled `C#` generator but enabled `resx` ?

Yes.

> And when you create new solution, and add new lhq file and try that steps, does not also stops regenerating resx? Or only on that big project?

I will try it.

>     * Do you save document to see changes regenerate?

No. Even when using "Save all" the resx is not regenerated.

>     * Are files that are generated by LHQ readonly, in source control, or ?
No, all files are r/w.

**Comment by psulek** [comment]
if you can isolate that bug in new sample project, it will be super. You can strip down all resources except left at least 1 resource and all languages and send *.lhq and *.lhq.tt files ?

**Comment by xorxx** [comment]
I am currently creating a sample project.

I installed LHQ Editor for an existing project and did not start with one of the LHQ templates. May this be a cause for this issue?

**Comment by psulek** [comment]
Its hard to tell :-| If sample project is working fine with LHQ, then try to send me *.lhq and *.lhq.tt files from that big project where it fails. You can left only 1 resources (and if possible all languages) so i can look at it. Also maybe csproj file (remove references, assembly name, etc, any private stuff) This may help also to analyse further.

**Comment by xorxx** [comment]
With a new project created from your template, I have no trouble and the generated files are all updating properly. But the project structure looks quite different compared to my project. Here is a clip from my project tree:
![grafik](https://user-images.githubusercontent.com/46751965/131360439-2c5197b7-13d5-4d25-81c7-a7775c360054.png)
The TL.de.resx and TL.en.resx files are properly updated. The file that is only sometimes generated is TL.Designer.cs.
The file TL.gen.cs is only generated when activating the c# code generation. I don't see that I need it for anything. This is why a deactivated c# code generation.

A few things are unclear to me:

1. Why is TL.resx generated at all? I activated the option "Filename for primary language includes language code":
![grafik](https://user-images.githubusercontent.com/46751965/131361370-3907e58f-e673-43e0-bdde-d7526ec8f4a9.png)

1. TL.Designer.cs seems to be the file with the strong definitions of the string getter function. Is this generated by LHQ edit or by visual studio?

Thanks for your support.

**Comment by psulek** [comment]
Maybe there is problem with `Output folder` to have path deliminer `\`. Please try move *.lhq and *.lhq.tt into root of project, and change settings to such:

![image](https://user-images.githubusercontent.com/2369743/131454445-dad9cab9-5455-48be-bcdb-d42d91c46975.png)

So `Output folder` will point to `Resources` within project.

**Comment by xorxx** [comment]
Finally i could track down the problem: It results from using the option "File name for primary language includes language code". The compiler seems to rely on a default resource file. Only for this one the "TL.designer.cs"  is created. The language specific files are by default all empty.  Therefore the string objects are all undefined in source code. At least this solution works for me.

**Comment by psulek** [comment]
Ok, but i tested on my env with exact settings you have and dont have problems. Maybe its combination with project folders structure. Can you write down project structure (folders) where you have *.lhq.* files?

But why u dont use generated C# classes? Its better for use strongly typed than resx. It also supports Culture change, You can see samples when you create new template project with `LHQ` prefix.

**Comment by xorxx** [comment]
The strongly typed c# classes are created by the resource compiler as far as i understood. Therefore I didn't see why I should use a different generator. I tried to use it, but didn't get it integrated in my project. Maybe my fault.

The Project structure looks like this:

- src
  - misc
    - Strings.lhq
    - TL.resx
      - TL.Designer.cs
    - TL.en.resx
      - TL.en.Designer.cs

Strings are called from namespace `src.misc.TL.`

**Comment by psulek** [comment]
Thanks for structure i will look at it why it fails. 
I highly recommend to look at LHQ project templates (wpf, asp.net, winforms) to see a real power of generated C# classes from LHQ C# class generator.

**Comment by psulek** [comment]
I tried your structure and everything works fine. Thing is when i play with checkbox **File name for primary language includes language code** then file with and without primary lang (resx) is created, eg. TL.resx and TL.en.resx. And then when changes are made and saved only one (current to actual value of that checkbox) is updated but not both. 
This can be the case, at least from my testing.

LHQ editor does not delete previously generated files (for obvious reason) so there can be some kind of "chaos" when you play with settings.

When you have such problems, i recommend to export resources to Excel file, remove all `lhq` related files, generated `resx` files, and create new LHQ file (using New Item Wizard) and then import resources back from that Excel file.

**Comment by xorxx** [comment]
Thank you very much for your support! I really like your tool.

**Comment by psulek** [comment]
> Thank you very much for your support! I really like your tool.

Thanks mate, those words are reason why i am doing it (y)
