### ISSUE TITLE
No Template Available in VS 2022

### ISSUE THREAD

**Issue by DavidPressman** [scalehq/lhq#6]
**Select category**
- [x] LHQ Editor - Visual Studio Extension
- [ ] NuGet Package - `ScaleHQ.WPF.LHQ(StrongName)`
- [ ] NuGet Package - `ScaleHQ.AspNetCore.LHQ(StrongName)`

**Version**
2021.1

**Visual Studio Edition**
- [ ] Visual Studio Community
- [ ] Visual Studio Pro
- [x] Visual Studio Enterprise

**Visual Studio Version**
- [x] 2015
- [x] 2017
- [x] 2019
- [x] 2022

**Describe Problem**
When installed as LHQ Editor VS2022 no templates appear when wanting to add new lhq file.
Workaround: Open solution in VS 2019 with the LHQ Editor for VS2019 installed, add file, close and return to VS 2022.

**Comment by psulek** [comment]
Known bug. I just released vs2022 release of extension because of vs2022 release. Sadly i don't have time to do full test of extension in it. 
Will look at vs2022 issues soon.

**Comment by DavidPressman** [comment]
I thought something of the sort might be the case. I look forward to whatever you are able to do. Thank you.

________________________________

**Comment by psulek** [comment]
This seems to be problem for all VS version using LHQ version 2021.1

**Comment by psulek** [comment]
Fixed in version **2021.3**
