### ISSUE TITLE
Cannot translate more than 16 languages using Microsoft Translator plugin

### ISSUE THREAD

**Issue by DavidPressman** [scalehq/lhq#7]
**Select category**
- [x] LHQ Editor - Visual Studio Extension
- [ ] NuGet Package - `ScaleHQ.WPF.LHQ(StrongName)`
- [ ] NuGet Package - `ScaleHQ.AspNetCore.LHQ(StrongName)`

**Version**
2021.1

**Visual Studio Edition**
- [ ] Visual Studio Community
- [ ] Visual Studio Pro
- [x] Visual Studio Enterprise

**Visual Studio Version**
- [ ] 2015
- [ ] 2017
- [x] 2019
- [x] 2022

**Describe Problem**
My original VS2019 WPF .Net Core app has 26 languages translated via Multilingual App Toolkit, which apparently will not be available for VS2022 (at least so far), so decided to try LHQ. After translating 16 languages (each with about 5,000 entries), all attempts to translate remaining languages fail. Can find no explanation in my Azure Portal.

**Comment by DavidPressman** [comment]
I was slightly off in my count of translatable languages: including source language: 18.
Workaround until fixed: Start second .lhq , repeat therein source language and translate remaining languages.
Requires writing additional utilization code to dynamically switch between translation sets during app run. Hardly ideal.

**Comment by psulek** [comment]
1st did you try it with Yandex translator?
Anyway can u provide list of all languages u have? (short code)

**Comment by DavidPressman** [comment]
Yandex seems too expensive. I've described my workaround in my comment today. Actually, number of languages was stated correctly in my original post; please ignore the updated count in today's comment.
Thanks again.

DP

________________________________

**Comment by psulek** [comment]
And can u provide list of languages? Or better attach lhq file here (all languages, with 1 resource is enough).

**Comment by DavidPressman** [comment]
Attached is screenshot of Resources folder's files, as generated by LHQ. All now I lack are the 2 Chinese files.

________________________________

**Comment by psulek** [comment]
@DavidPressman i could not find screenshot. Can list type list of all languages u using? Or edit your existing LHQ file, clear all resources (except 1) and leave all languages defined and add this lhq file to this github issues?

**Comment by psulek** [comment]
@DavidPressman There are maybe problem with free version of M$ Cognitive translator (if u using this free option). 

If u look at price calculator page (https://azure.microsoft.com/en-us/pricing/calculator/?service=cognitive-services) , there is mention **Max. transactions included: 5,000** 

![image](https://user-images.githubusercontent.com/2369743/141769361-136e6c02-1777-40e4-b4e9-17201f3bdddc.png)

If i get it correctly than this is limit of FREE instance.

I made test with 20 languages and 2 resources and all languges was successfully translated. Maybe if i get 5000 resources i will get same error as you describe. 

Or do u use paid version of Cognitive services ?

**Comment by DavidPressman** [comment]
I am Pay as you go, Standard Plan S1.
Current cost so far this billing cycle is $81.72 (see attached screenshot), nearly all of it trying to get LHQ to work as desired.
That compares to $0.20 in the previous billing period.

I did create a Test LHQ with all desired languages.
When I simply added one test resource all languages except Chinese got translated.
However, when I deleted that single resource and imported my 4,952 existing ones from the earlier VS 2019 solution, only English was translated.
That result is also attached.

In view of my high incurred cost trying to get LHQ to work, I will discontinue further efforts for now.
Nonetheless, I do hope the issues get resolved.
Thank you for all your efforts.

David Pressman

________________________________

**Comment by psulek** [comment]
@DavidPressman sorry to hear that man. Everyone i know using this little extension on projects with low count of languages (usually <10) and low count of resources (< 1k) and without active usage of translator service. 
I will try to look at it anyway for any other developers who can suffer from such failtures.

Btw how you add those github comments? Because it does not shows me any screenshot nor attachment.

**Comment by DavidPressman** [comment]
I am replying by email. I guess github must be stripping my attachments. Is there a personal or other business email address I can send to?

David Pressman


________________________________

**Comment by psulek** [comment]
i get it now, thanks.

**Comment by scalehq** [comment]
Fixed in release [2021.6](https://github.com/psulek/lhqeditor/releases/tag/v2021.6)
