### ISSUE TITLE
In VS 2022, cannot translate to either Simplified or Traditional Chinese with Microsoft Translator

### ISSUE THREAD

**Issue by DavidPressman** [scalehq/lhq#8]
**Select category**
- [x] LHQ Editor - Visual Studio Extension
- [ ] NuGet Package - `ScaleHQ.WPF.LHQ(StrongName)`
- [ ] NuGet Package - `ScaleHQ.AspNetCore.LHQ(StrongName)`

**Version**
2021.1

**Visual Studio Edition**
- [ ] Visual Studio Community
- [ ] Visual Studio Pro
- [x] Visual Studio Enterprise

**Visual Studio Version**
- [ ] 2015
- [ ] 2017
- [ ] 2019
- [x] 2022

**Describe Problem**
I have existing translations to both zh-Hans and zh-Hant from VS 2019 using the Multilingual App Toolkit, but cannot duplicate these with LHQ after moving solution to VS 2022. Instead LHQ reports neither is supported by Microsoft Translate, which is clearly not true.

**Comment by psulek** [comment]
I got error messages from translator API. Maybe Multilingual uses some special only for MS API key to bypass limitation of their API, I don't known.

That being said I will try to find out what's wrong.

**Comment by DavidPressman** [comment]
Thank you.

________________________________

**Comment by psulek** [comment]
Fixed in version **2021.4**
